package speedfan;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nathan
 */
public class Report extends javax.swing.JFrame {

    private static int BLUE = 0;
    private static int RED = 1;
    private static int GREEN = 2;
    private static int YELLOW = 3; 
    private static int ORANGE = 4;
    private static int DARK = 5;
    private static int PURPLE = 6;
    private int colorState;
    
    //Darkest to lightest
    private static Color[] BLUE_ARRAY = {new Color(0, 0, 102), new Color(0, 153, 255), new Color(153,204,255), new Color(153,204,255)}; 
    private static Color[] RED_ARRAY = {new Color(204,0,0), new Color(255, 0, 0), new Color(255, 102, 102)};
    private static Color[] GREEN_ARRAY = {new Color(0,102,0), new Color(0,204,0), new Color(102, 255, 102)};
    private static Color[] YELLOW_ARRAY = {new Color(255,204,0), new Color(255, 255, 0), new Color(255, 255, 204)};
    private static Color[] ORANGE_ARRAY = {new Color(255,102,0), new Color(255, 204, 51), new Color(255, 153, 0)};
    private static Color[] DARK_ARRAY = {new Color(51,51,51), new Color(102,102, 102), new Color(204, 204, 204)};
    private static Color[] PURPLE_ARRAY = {new Color(102,0,153), new Color(218, 112, 214), new Color(216, 191, 216)};
    
    
    private Help help;
    private Home home;
    private Settings settings;
    
    private boolean helpOpened = false;
    private boolean settingsOpened = false;
    
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        colorState = BLUE;
        reportBackground.setBackground(setColor("BRIGHT"));
        bottomBanner.setBackground(setColor("DARK"));
        innerBorder.setBackground(setColor("BRIGHT"));
        
        this.setSize(425, 386);
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("Images/New Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reportBackground = new javax.swing.JPanel();
        motherboardModelTextField = new javax.swing.JTextField();
        motherboardText = new javax.swing.JLabel();
        motherboardText1 = new javax.swing.JLabel();
        emailAddressTextField = new javax.swing.JTextField();
        bottomBanner = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        innerBorder = new javax.swing.JPanel();
        question1Text = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        dontKnow = new javax.swing.JRadioButton();
        question1Text1 = new javax.swing.JLabel();
        yes1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        dontKnow1 = new javax.swing.JRadioButton();
        question1Text2 = new javax.swing.JLabel();
        yes2 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        dontKnow2 = new javax.swing.JRadioButton();
        httpProxyText = new javax.swing.JLabel();
        httpProxyTextField = new javax.swing.JTextField();
        portText = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        userNameText = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        reportBackground.setBackground(new java.awt.Color(153, 204, 255));

        motherboardModelTextField.setText("Motherboard1");
        motherboardModelTextField.setToolTipText("This was automatically filled for you :)");
        motherboardModelTextField.setEnabled(false);

        motherboardText.setText("Motherboard Model");

        motherboardText1.setText("Email Address");

        bottomBanner.setBackground(new java.awt.Color(0, 0, 153));
        bottomBanner.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tick.png"))); // NOI18N
        okButton.setText("OK");
        okButton.setToolTipText("Send report");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cross.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Cancel report");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomBannerLayout = new javax.swing.GroupLayout(bottomBanner);
        bottomBanner.setLayout(bottomBannerLayout);
        bottomBannerLayout.setHorizontalGroup(
            bottomBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomBannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        bottomBannerLayout.setVerticalGroup(
            bottomBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomBannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        innerBorder.setBackground(new java.awt.Color(153, 204, 255));
        innerBorder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        question1Text.setText("Can you change fan speeds?");

        yes.setBackground(new java.awt.Color(153, 204, 255));
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setBackground(new java.awt.Color(153, 204, 255));
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        dontKnow.setBackground(new java.awt.Color(153, 204, 255));
        dontKnow.setText("Don't know");
        dontKnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontKnowActionPerformed(evt);
            }
        });

        question1Text1.setText("Smoothly?");

        yes1.setBackground(new java.awt.Color(153, 204, 255));
        yes1.setText("Yes");
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        no1.setBackground(new java.awt.Color(153, 204, 255));
        no1.setText("No");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        dontKnow1.setBackground(new java.awt.Color(153, 204, 255));
        dontKnow1.setText("Don't know");
        dontKnow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontKnow1ActionPerformed(evt);
            }
        });

        question1Text2.setText("Can you stop fans?");

        yes2.setBackground(new java.awt.Color(153, 204, 255));
        yes2.setText("Yes");
        yes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes2ActionPerformed(evt);
            }
        });

        no2.setBackground(new java.awt.Color(153, 204, 255));
        no2.setText("No");
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });

        dontKnow2.setBackground(new java.awt.Color(153, 204, 255));
        dontKnow2.setText("Don't know");
        dontKnow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontKnow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout innerBorderLayout = new javax.swing.GroupLayout(innerBorder);
        innerBorder.setLayout(innerBorderLayout);
        innerBorderLayout.setHorizontalGroup(
            innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question1Text)
                    .addComponent(question1Text1)
                    .addComponent(question1Text2))
                .addGap(18, 18, 18)
                .addGroup(innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerBorderLayout.createSequentialGroup()
                        .addComponent(yes2)
                        .addGap(18, 18, 18)
                        .addComponent(no2)
                        .addGap(18, 18, 18)
                        .addComponent(dontKnow2))
                    .addGroup(innerBorderLayout.createSequentialGroup()
                        .addComponent(yes)
                        .addGap(18, 18, 18)
                        .addComponent(no)
                        .addGap(18, 18, 18)
                        .addComponent(dontKnow))
                    .addGroup(innerBorderLayout.createSequentialGroup()
                        .addComponent(yes1)
                        .addGap(18, 18, 18)
                        .addComponent(no1)
                        .addGap(18, 18, 18)
                        .addComponent(dontKnow1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        innerBorderLayout.setVerticalGroup(
            innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1Text)
                    .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dontKnow, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1Text1)
                    .addComponent(yes1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dontKnow1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(innerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1Text2)
                    .addComponent(yes2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dontKnow2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        httpProxyText.setText("HTTP Proxy");

        portText.setText("Port");

        userNameText.setText("Username");

        passwordText.setText("Password");

        javax.swing.GroupLayout reportBackgroundLayout = new javax.swing.GroupLayout(reportBackground);
        reportBackground.setLayout(reportBackgroundLayout);
        reportBackgroundLayout.setHorizontalGroup(
            reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(reportBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(innerBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reportBackgroundLayout.createSequentialGroup()
                        .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motherboardText)
                            .addComponent(motherboardText1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailAddressTextField)
                            .addComponent(motherboardModelTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportBackgroundLayout.createSequentialGroup()
                        .addComponent(httpProxyText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(httpProxyTextField)
                        .addGap(18, 18, 18)
                        .addComponent(portText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportBackgroundLayout.createSequentialGroup()
                        .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameText)
                            .addComponent(passwordText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTextField)
                            .addComponent(usernameTextField))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        reportBackgroundLayout.setVerticalGroup(
            reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherboardText)
                    .addComponent(motherboardModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherboardText1)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(innerBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpProxyText)
                    .addComponent(httpProxyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portText)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameText)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(reportBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bottomBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reportBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(settings != null)
        {
            settings.setReport(null);
        }
        
        if(home != null)
        {
            home.setReportClosed();
            
        }
    }//GEN-LAST:event_formWindowClosed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        if(yes.isEnabled()){
            no.setEnabled(false);
            dontKnow.setEnabled(false);
        }
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        if(no.isEnabled()){
            yes.setEnabled(false);
            dontKnow.setEnabled(false);
        }
    }//GEN-LAST:event_noActionPerformed

    private void dontKnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontKnowActionPerformed
        if(dontKnow.isEnabled()){
            no.setEnabled(false);
            yes.setEnabled(false);
        }
    }//GEN-LAST:event_dontKnowActionPerformed

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        if(yes1.isEnabled())
        {
            no1.setEnabled(false);
            dontKnow1.setEnabled(false);
        }
    }//GEN-LAST:event_yes1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        if(no1.isEnabled())
        {
            yes1.setEnabled(false);
            dontKnow1.setEnabled(false);
        }
    }//GEN-LAST:event_no1ActionPerformed

    private void dontKnow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontKnow1ActionPerformed
        if(dontKnow1.isEnabled())
        {
            yes1.setEnabled(false);
            no1.setEnabled(false);
        }
    }//GEN-LAST:event_dontKnow1ActionPerformed

    private void yes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes2ActionPerformed
        if(yes2.isEnabled())
        {
            no2.setEnabled(false);
            dontKnow2.setEnabled(false);
        }
    }//GEN-LAST:event_yes2ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
        if(no2.isEnabled())
        {
            yes2.setEnabled(false);
            dontKnow2.setEnabled(false);
        }
    }//GEN-LAST:event_no2ActionPerformed

    private void dontKnow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontKnow2ActionPerformed
        if(dontKnow2.isEnabled())
        {
            no2.setEnabled(false);
            yes2.setEnabled(false);
        }
    }//GEN-LAST:event_dontKnow2ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
        dispose(); 
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose(); 
    }//GEN-LAST:event_cancelButtonActionPerformed

      
    
    
    
    
    
    public void setHelp(Help help)
    {
        if(help != null)
        {
            this.help = help;
            helpOpened = true;
        }
        else
        {
            this.help = null;
            helpOpened = false;
        }
        
    }
    
    public void setSettings(Settings settings)
    {
        if(settings != null)
        {
            settingsOpened = true;
            this.settings = settings;
        }
        else
        {
            settingsOpened = false;
            this.settings = null;
        }
    }
    
    public void setSettingsClosed()
    {
        settingsOpened = false;
        this.settings = null;
    }
    
    public void setHome(Home home)
    {
        this.home = home;
        this.home.setReport(Report.this);
    }
    
    public void changeColorScheme(int colorState){
        this.colorState = colorState;
        
        reportBackground.setBackground(setColor("BRIGHT"));
        bottomBanner.setBackground(setColor("DARK"));
        innerBorder.setBackground(setColor("BRIGHT"));
    
    }
    
    private Color setColor(String prompt)
    {
        Color color = null;
        if(prompt.equals("MEDIUM"))
        {
            color = pickTone(1);
            
        }
        else if(prompt.equals("DARK"))
        {
            color = pickTone(0);
        }
        else if(prompt.equals("BRIGHT"))
        {
            color = pickTone(2);
        }
        else if(prompt.equals("OTHER"))
        {
            color = pickTone(3);
        }
        return color;
        
    }
    
    private Color pickTone(int index)
    {
        Color color = null;
        if(colorState == BLUE)
            {
                color = BLUE_ARRAY[index];
            }
            else if(colorState == RED)
            {
                color = RED_ARRAY[index];
            }
            else if(colorState == GREEN)
            {
                color = GREEN_ARRAY[index];
            }
            else if(colorState == YELLOW)
            {
                color = YELLOW_ARRAY[index];
            }
            else if(colorState == ORANGE)
            {
                color = ORANGE_ARRAY[index];
            }
            else if(colorState == DARK)
            {
                color = DARK_ARRAY[index];
            }
            else if(colorState == PURPLE)
            {
                color = PURPLE_ARRAY[index];
            }
        return color;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomBanner;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton dontKnow;
    private javax.swing.JRadioButton dontKnow1;
    private javax.swing.JRadioButton dontKnow2;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel httpProxyText;
    private javax.swing.JTextField httpProxyTextField;
    private javax.swing.JPanel innerBorder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField motherboardModelTextField;
    private javax.swing.JLabel motherboardText;
    private javax.swing.JLabel motherboardText1;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel passwordText;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel portText;
    private javax.swing.JTextField portTextField;
    private javax.swing.JLabel question1Text;
    private javax.swing.JLabel question1Text1;
    private javax.swing.JLabel question1Text2;
    private javax.swing.JPanel reportBackground;
    private javax.swing.JLabel userNameText;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JRadioButton yes;
    private javax.swing.JRadioButton yes1;
    private javax.swing.JRadioButton yes2;
    // End of variables declaration//GEN-END:variables
}
